workflows:
  android-java-debug:
    name: Android Java Debug APK
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      java: 17

    scripts:
      - name: Show project files
        script: |
          ls -la
          ls -la app

      - name: Build debug APK
        script: |
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
            ./gradlew assembleDebug
          else
            gradle assembleDebug
          fi

    artifacts:
      - app/build/outputs/**/*.apk
